# Generated by Django 5.0.6 on 2024-06-19 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assetapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="document",
            field=models.FileField(upload_to="uploads/"),
        ),
    ]
